### ISSUE TITLE
javac.exe Invalid Argument Error- Scanner module

### ISSUE THREAD

**Issue by tahersb** [mwrlabs/drozer#165]
Hi,
I am running drozer v2.3.4 on windows 7 with JDK 6.45.

I experience the error as below when I execute the following command: 

`dz> run scanner.provider.finduris -a com.app.apps`

Error in debug mode: 

C:\Program Files\Java\jdk1.6.0_45\bin\javac.exe" -cp E:\Tools\drozer\lib\drozer\lib\android.jar ZipUtil.java
exception in module: OSError: [Errno 22] Invalid argument
Traceback (most recent call last):

  File "E:\Tools\drozer\lib\drozer\console\session.py", line 394, in do_run
    module.run(argv[1:])
  File "E:\Tools\drozer\lib\drozer\modules\base.py", line 183, in run
    result = self.execute(arguments)
  File "E:\Tools\drozer\lib\drozer\modules\scanner\provider\find_uris.py", line 23, in execute
    for uri in self.findAllContentUris(arguments.package):
  File "E:\Tools\drozer\lib\drozer\modules\common\provider.py", line 206, in findAllContentUris
    uris = uris.union(self.__search_package(package))
  File "E:\Tools\drozer\lib\drozer\modules\common\provider.py", line 316, in __search_package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "E:\Tools\drozer\lib\drozer\modules\common\provider.py", line 228, in findContentUris
    dex_file = self.extractFromZip("classes.dex", path, self.cacheDir())
  File "E:\Tools\drozer\lib\drozer\modules\common\zip_file.py", line 14, in extractFromZip
    ZipUtil = self.loadClass("common/ZipUtil.apk", "ZipUtil")
  File "E:\Tools\drozer\lib\drozer\modules\common\loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "E:\Tools\drozer\lib\pydiesel\reflection\utils\class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "E:\Tools\drozer\lib\pydiesel\reflection\utils\class_loader.py", line 36, in getClassLoader
    self.source = self.__get_source(self.source_or_relative_path, relative_to=self.relative_to)
  File "E:\Tools\drozer\lib\pydiesel\reflection\utils\class_loader.py", line 80, in __get_source
    source = ClassBuilder(java_path, self.dx_path(), self.javac_path(), self.android_path()).build()
  File "E:\Tools\drozer\lib\pydiesel\reflection\utils\class_builder.py", line 36, in build
    if not self.__execute(self.javac , "-cp", self.sdk_path, os.path.basename(self.path)):
  File "E:\Tools\drozer\lib\pydiesel\reflection\utils\class_builder.py", line 68, in __execute
    return os.spawnve(os.P_WAIT, argv[0], argv, os.environ) == 0
OSError: [Errno 22] Invalid argument

Is there a workaround for this?

**Comment by KingDragon08** [comment]
I have the issue like you,how you deal with it in the last?
here is my debug info

dz> run scanner.provider.finduris -a com.mwr.example.sieve
Scanning com.mwr.example.sieve...
exception in module: ReflectionException: cannot resolve com.mwr.jdiesel.util.Strings
Traceback (most recent call last):
  File "c:\drozer\lib\drozer\console\session.py", line 394, in do_run
    module.run(argv[1:])
  File "c:\drozer\lib\drozer\modules\base.py", line 183, in run
    result = self.execute(arguments)
  File "C:\drozer\lib\drozer\modules\scanner\provider\find_uris.py", line 23, in execute
    for uri in self.findAllContentUris(arguments.package):
  File "c:\drozer\lib\drozer\modules\common\provider.py", line 206, in findAllContentUris
    uris = uris.union(self.__search_package(package))
  File "c:\drozer\lib\drozer\modules\common\provider.py", line 316, in __search_package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "c:\drozer\lib\drozer\modules\common\provider.py", line 231, in findContentUris
    strings = self.getStrings(dex_file.getAbsolutePath())
  File "c:\drozer\lib\drozer\modules\common\strings.py", line 12, in getStrings
    StringsKlass = self.klass("com.mwr.jdiesel.util.Strings")
  File "c:\drozer\lib\drozer\modules\base.py", line 137, in klass
    Module.cache_klass(class_name, self.reflector.resolve(class_name))
  File "c:\drozer\lib\pydiesel\reflection\reflector.py", line 98, in resolve
    raise ReflectionException(response.reflection_response.errormessage)
ReflectionException: cannot resolve com.mwr.jdiesel.util.Strings

**Comment by raulsiles** [comment]
@tahersb Please, take a look at Issue #130 (related to this one).

You can fix the current bug by manually compiling the APK with the following two commands:
C:\>javac -cp C:\drozer\Lib\drozer\lib\android.jar C:\drozer\Lib\drozer\modules\common\ZipUtil.java

C:\>C:\Users\student\AppData\Local\Android\sdk\build-tools\19.1.0\dx.bat --dex --no-strict --output=C:\drozer\Lib\drozer\modules\common\ZipUtil.apk C:\drozer\Lib\drozer\modules\common\ZipUtil.class

After that, you will suffer issue #170 mentioned by @KingDragon08. 

I have found the missing String class in the MWR jdiesel GitHub project (https://github.com/mwrlabs/jdiesel/blob/master/src/com/mwr/jdiesel/util/Strings.java), but... what is the best method to include it inside Drozer?

**Comment by piaodangdang** [comment]
I have compiled the APK manually,still mentioned "cannot resolve com.mwr.jdiesel.util.Strings"

**Comment by amarekano** [comment]
Hi @piaodangdang, please try our latest drozer release and open a new issue if you're still having trouble getting this working.
The latest release can be found at https://github.com/mwrlabs/drozer/releases/tag/2.4.2
