### ISSUE TITLE
Cannot resolve com.mwr.jdiesel.util.Strings-Scanner Module-Win7

### ISSUE THREAD

**Issue by KingDragon08** [mwrlabs/drozer#170]
I'm having issues when using drozer,anyone have ideas?Thanks a lot
below is the debug info.

dz> run scanner.provider.finduris -a com.mwr.example.sieve
Scanning com.mwr.example.sieve...
exception in module: ReflectionException: cannot resolve com.mwr.jdiesel.util.Strings
Traceback (most recent call last):
  File "c:\drozer\lib\drozer\console\session.py", line 394, in do_run
    module.run(argv[1:])
  File "c:\drozer\lib\drozer\modules\base.py", line 183, in run
    result = self.execute(arguments)
  File "C:\drozer\lib\drozer\modules\scanner\provider\find_uris.py", line 23, in execute
    for uri in self.findAllContentUris(arguments.package):
  File "c:\drozer\lib\drozer\modules\common\provider.py", line 206, in findAllContentUris
    uris = uris.union(self.__search_package(package))
  File "c:\drozer\lib\drozer\modules\common\provider.py", line 316, in __search_package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "c:\drozer\lib\drozer\modules\common\provider.py", line 231, in findContentUris
    strings = self.getStrings(dex_file.getAbsolutePath())
  File "c:\drozer\lib\drozer\modules\common\strings.py", line 12, in getStrings
    StringsKlass = self.klass("com.mwr.jdiesel.util.Strings")
  File "c:\drozer\lib\drozer\modules\base.py", line 137, in klass
    Module.cache_klass(class_name, self.reflector.resolve(class_name))
  File "c:\drozer\lib\pydiesel\reflection\reflector.py", line 98, in resolve
    raise ReflectionException(response.reflection_response.errormessage)
ReflectionException: cannot resolve com.mwr.jdiesel.util.Strings

**Comment by raulsiles** [comment]
I have found the missing String class in the MWR jdiesel GitHub project (https://github.com/mwrlabs/jdiesel/blob/master/src/com/mwr/jdiesel/util/Strings.java), but... what is the best method to include it inside Drozer?

**Comment by zhangbaocheng** [comment]
I alse have the bug when using the emulator.
The error message is this:
cannot resolve com.mwr.jdiesel.util.Strings
when I use the real device,the bug is gone.
And I couldn't figure it out.

**Comment by Andy10101** [comment]
I also encountered the same problem
previous versions of agent.apk can solve this bug

**Comment by amarekano** [comment]
Hi all, could you try our latest drozer release and open a new issue if you're still having trouble getting this working.
The latest release can be found at https://github.com/mwrlabs/drozer/releases/tag/2.4.2
