### ISSUE TITLE
drozer(python.egg) link is broken

### ISSUE THREAD

**Issue by JoyMitra** [mwrlabs/drozer#220]
### Steps to reproduce
1. go to https://labs.mwrinfosecurity.com/tools/drozer/
2. try to download drozer (Python .egg)
3. link is broken

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Environment

**Operating system**: MAC OS X (El Capitan)

**Java Version:** 1.6

**Android Version:** Android 6.0

**Drozer Version:** 

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by HenryHoggard** [comment]
Yes, thanks for the report, we are aware. The download links were lost in creation of the new website -_-. I'm trying to hunt them down.

**Comment by HenryHoggard** [comment]
@JoyMitra I'm still trying to find the lost 2.3.4 releases. In the meantime I've pushed out a prerelease .egg here https://github.com/mwrlabs/drozer/releases/tag/2.4.0

**Comment by JoyMitra** [comment]
@HenryHoggard  Thank you for the prerelease. However, I am getting the following error. Am I doing something wrong or is their something wrong with the script?

This is the error I get when I try to install drozer:

$ sudo easy_install drozer-2.4.0-py2.7.egg 
Processing drozer-2.4.0-py2.7.egg
creating /Library/Python/2.7/site-packages/drozer-2.4.0-py2.7.egg
Extracting drozer-2.4.0-py2.7.egg to /Library/Python/2.7/site-packages
Adding drozer 2.4.0 to easy-install.pth file
Installing drozer script to /usr/local/bin
Installing drozer-complete script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/drozer-2.4.0-py2.7.egg
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==1.1.6', 'console_scripts', 'easy_install')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1925, in main
    with_ei_usage(lambda:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1912, in with_ei_usage
    return f()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1929, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 374, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 590, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 641, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 682, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by JoyMitra** [comment]
@HenryHoggard It works now. It seems like I missed quite a few dependencies. These dependencies are not documented in the Drozer User Guide. I found them at this link https://blog.ropnop.com/installing-drozer-on-os-x-el-capitan/.

Here is a complete list of dependencies that I had to install for drozer to build. Also turns out if you are using el capitan OS-X then it is a better idea to install your own python2.7 as opposed to the default one:
cffi (1.7.0)
cryptography (1.5)
drozer (2.4.0)
idna (2.1)
ipaddress (1.0.16)
pip (8.1.2)
protobuf (2.6.1)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (0.15)
PyYAML (3.11)
setuptools (23.0.0)
six (1.9.0)
Twisted (10.2.0)
wheel (0.29.0)
zope.interface (4.3.1)

You might want to update the user guide with all this info.

Thanks again for the prerelease. I hope to use drozer now.

**Comment by HenryHoggard** [comment]
@JoyMitra thanks, we will add these dependencies to the user guide.

**Comment by JoyMitra** [comment]
@HenryHoggard Can you please give me the Drozer.apk file? It is not present in the release tarball and the download links are broken. It would be really helpful

**Comment by JoyMitra** [comment]
Thank You.
