### ISSUE TITLE
drozer 2.4.0 could not find or compile a required extension library

### ISSUE THREAD

**Issue by razvanionescu** [mwrlabs/drozer#225]
### Steps to reproduce
1. drozer console connect -c "run app.package.manifest com.android.chrome"
   or any other command from below against any package app installed on the Android device:

run app.package.native
run app.activity.info
run app.service.info
run scanner.misc.native
run scanner.provider.finduris
run scanner.provider.injection
run scanner.provider.sqltables
run scanner.provider.traversal
run app.provider.finduri

and probably more others ....
### Expected behaviour

Tell us what should happen.
The commands should give you the expected output related to each command.
### Actual behaviour

Tell us what happens instead.
The following message is displayed:
drozer could not find or compile a required extension library
### Environment

**Operating system**:
Kali 2.0

**Java Version:**

**Android Version:**
6.0.1

**Drozer Version:** 
2.4.0

**Install Method:** Using the .egg file from here: https://github.com/mwrlabs/drozer/releases/tag/2.4.0-alpha
### Drozer Config

```
Contents of ~/.drozer_config
```
### Drozer Error Logs

```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
### ADB Logs

```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by HenryHoggard** [comment]
Thanks for the report, I've made a fix and I'm just testing it. I'll let you know when it is available.

**Comment by razvanionescu** [comment]
Hi Henry!
Do you have a status update regarding this fix, please?
Thank you in advance!
Best regards,
Razvan

**Comment by HenryHoggard** [comment]
Please try using the update .egg file. https://github.com/mwrlabs/drozer/releases/download/2.4.1/drozer-2.4.1-py2.7.egg

**Comment by riless** [comment]
This issue still exists in version 2.4.2. I'm working on an emulator

**Comment by HenryHoggard** [comment]
@riless did you use the .egg or compile from source.

**Comment by riless** [comment]
Yes.

```
$ sudo easy_install drozer-2.4.1-py2.7.egg
Processing drozer-2.4.1-py2.7.egg
removing '/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg' (and everything under it)
creating /Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg
Extracting drozer-2.4.1-py2.7.egg to /Library/Python/2.7/site-packages
drozer 2.4.1 is already the active version in easy-install.pth
Installing drozer script to /usr/local/bin
Installing drozer-complete script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==18.5', 'console_scripts', 'easy_install')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 2279, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 389, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 619, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 670, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 713, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
```

**Comment by riless** [comment]
@HenryHoggard I've compiled from source because .egg don't works.

```
$ sudo easy_install drozer-2.4.1-py2.7.egg
Processing drozer-2.4.1-py2.7.egg
removing '/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg' (and everything under it)
creating /Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg
Extracting drozer-2.4.1-py2.7.egg to /Library/Python/2.7/site-packages
drozer 2.4.1 is already the active version in easy-install.pth
Installing drozer script to /usr/local/bin
Installing drozer-complete script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==18.5', 'console_scripts', 'easy_install')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 2279, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 389, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 619, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 670, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 713, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
```

**Comment by razvanionescu** [comment]
Hi all,
It worked with drozer_2.3.4.deb (if you need a working reference version).
Thank you!
Best regards,
Razvan

**Comment by amarekano** [comment]
Hi @riless did you execute 'make apks' before building the egg from source?

**Comment by HenryHoggard** [comment]
@amarekano the `make apks` issue is due to a different error msg. https://github.com/mwrlabs/drozer/issues?utf8=%E2%9C%93&q=required%20extension
