### ISSUE TITLE
google.js is not in list

### ISSUE THREAD

**Issue by xl7dev** [mwrlabs/drozer#235]
drozer console connect
Traceback (most recent call last):
  File "/usr/local/bin/drozer", line 4, in <module>
    __import__('pkg_resources').run_script('drozer==2.4.1', 'drozer')
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1505, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/EGG-INFO/scripts/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/drozer/cli/console.py", line 8, in <module>
    from drozer.console import Console
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/drozer/console/__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/drozer/console/console.py", line 5, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/pydiesel/api/__init__.py", line 9, in <module>
    from pydiesel.api.frame import Frame
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/pydiesel/api/frame.py", line 3, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/Library/Python/2.7/site-packages/drozer-2.4.1-py2.7.egg/pydiesel/api/protobuf_pb2.py", line 3, in <module>
    from google.protobuf import descriptor
  File "/Library/Python/2.7/site-packages/protobuf-2.6.1-py2.7.egg/google/__init__.py", line 1, in <module>
    #
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2098, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2048, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2067, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2065, in position_in_sys_path
    return sys_path.index(_normalize_cached(os.sep.join(parts)))
ValueError: '/usr/local/lib/node_modules/google.js' is not in list

**Comment by HenryHoggard** [comment]
This doesn't appear to be an issue with Drozer.

**Comment by HenryHoggard** [comment]
Can you please provide more information. Are you using the .egg or did you build Drozer from source.

**Comment by xl7dev** [comment]
@HenryHoggard > easy_install drozer-2.4.1-py2.7.egg

**Comment by xl7dev** [comment]
@HenryHoggard drozer-2.4.2 successing install

**Comment by HenryHoggard** [comment]
Closing as Drozer 2.4.2 works. Let us know if you encounter this issue again.
