### ISSUE TITLE
Crash and lost connection when:run scanner.provider.finduris -a

### ISSUE THREAD

**Issue by Tangyiming** [mwrlabs/drozer#238]
```
D:\SecurityTools\drozer>adb forward tcp:31415 tcp:31415

D:\SecurityTools\drozer>drozer console connect --debug
Selecting c8ebd01e4a521e93 (InnoDezign LS-5004 5.1.1)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.3.4 debug mode)
dz> run scanner.provider.finduris -a com.xxxxxx.xxxxxxx
Scanning com.xxxxxx.xxxxxxx...
We lost your drozer session.

For some reason the mobile Agent has stopped responding. You will need to restart it, and try again.

[Errno 10053]


D:\SecurityTools\drozer>
```

log:

```
--------- beginning of crash

E/AndroidRuntime( 9939): FATAL EXCEPTION: Thread-515

E/AndroidRuntime( 9939): Process: com.mwr.dz:remote, PID: 9939

E/AndroidRuntime( 9939): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mwr.dz-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmstring.so"

E/AndroidRuntime( 9939): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)

E/AndroidRuntime( 9939): 	at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.util.Strings.<clinit>(Strings.java:6)

E/AndroidRuntime( 9939): 	at java.lang.Class.classForName(Native Method)

E/AndroidRuntime( 9939): 	at java.lang.Class.forName(Class.java:309)

E/AndroidRuntime( 9939): 	at java.lang.Class.forName(Class.java:273)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.reflection.Reflector.resolve(Reflector.java:138)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.api.handlers.ReflectionMessageHandler.handleResolve(ReflectionMessageHandler.java:193)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.api.handlers.ReflectionMessageHandler.handle(ReflectionMessageHandler.java:66)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.api.sessions.Session.handleMessage(Session.java:35)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.connection.AbstractSession.run(AbstractSession.java:76)

E/AndroidRuntime( 9939): 	at com.mwr.jdiesel.api.sessions.Session.run(Session.java:42)

I/Process ( 9939): Sending signal. PID: 9939 SIG: 9

D/BatteryTempPolicy(  779): getInstance

D/BatteryService(  779): sendIntentLocked<> mHandler 

D/BatteryTempPolicy(  779): onReceiveIntent android.intent.action.BATTERY_CHANGED

D/BatteryTempPolicy(  779): pickNextBatteryTempThreshold: Temperature = 316, mBatteryTempThreshold = 3

D/BatteryTempPolicy(  779): updateBatteryTemp temperature = 316, Threshhold = 3

D/HeadsetStateMachine( 6317): Disconnected process message: 10, size: 0

I/ActivityManager(  779): Process com.mwr.dz:remote (pid 9939) has died

W/ActivityManager(  779): Scheduling restart of crashed service com.mwr.dz/.services.ClientService in 143910ms

W/ActivityManager(  779): Scheduling restart of crashed service com.mwr.dz/.services.ServerService in 153910ms

D/StatusBar.MSimNetworkController( 4447): refreshViews phoneId =0mMSimDataConnected =false

D/StatusBar.MSimNetworkController( 4447): refreshViews mMSimDataActivity =0

D/wpa_supplicant( 4613): wlan0: Control interface command 'SIGNAL_POLL'

D/StatusBar.MSimNetworkController( 4447): refreshViews: Data not connected!! Set no data type icon / Roaming for phoneId: 0

D/StatusBar.MSimNetworkController( 4447): refreshViews connected={ wifi } level=0 mMSimcombinedSignalIconId=0x7f02034d/com.android.systemui:drawable/stat_sys_wifi_signal_4 mMSimcombinedActivityIconId=0x7f020344 mAirplaneMode=false mMSimDataActivity=0 mMSimPhoneSignalIconId=0x7f020334/com.android.systemui:drawable/stat_sys_signal_null mMSimDataDirectionIconId=0x0 mMSimDataSignalIconId=0x7f020334 mMSimDataTypeIconId=0x0/(null) mNoMSimIconId=0x7f02008b/com.android.systemui:drawable/ic_qs_no_sim mMSimMobileActivityIconId=0x0/(null) mWifiIconId=0x7f02034d mBluetoothTetherIconId=0x108069e
```

enviroments:

```
os:win7 x64
android:5.1.1
drozer version:2.3.4
java version:1.6
```

**Comment by HenryHoggard** [comment]
Can you try Drozer 2.4.1 and see if this still happens?

**Comment by Tangyiming** [comment]
@HenryHoggard i tried 2.4.1 and it didn't work too. then i reinstall drozer 2.3.4.exe ,python2.7 and  java 1.6, install sdk,ndk,cmake,lldb from sdk manage--sdk tolls,and set path like this:
```
path:
C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;D:\Android_Studio_SDK\tools;C:\drozer\bin;
PYTHONPATH:
C:\Python27
```
and solved the crash problem
 i think the problem is caused by enviroments path settings and sdk tools. 
hope it's helpful for everyone have the problem like me
