### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT

### ISSUE THREAD

**Issue by HenryHoggard** [mwrlabs/drozer#239]
### Steps to reproduce
1. `drozer console connect --server 192.168.0.15`

### Actual behaviour
```
Traceback (most recent call last):
  File "/usr/local/bin/drozer", line 4, in <module>
    __import__('pkg_resources').run_script('drozer==2.4.1', 'drozer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/EGG-INFO/scripts/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/drozer/cli/console.py", line 8, in <module>
    from drozer.console import Console
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/drozer/console/__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/drozer/console/console.py", line 6, in <module>
    from pydiesel.api.transport.exceptions import ConnectionError
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/pydiesel/api/transport/__init__.py", line 5, in <module>
    from socket_transport import SocketTransport
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/pydiesel/api/transport/socket_transport.py", line 8, in <module>
    from drozer.ssl.provider import Provider # TODO: eugh
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/drozer/ssl/__init__.py", line 1, in <module>
    from drozer.ssl.ssl_manager import SSLManager
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/drozer/ssl/ssl_manager.py", line 6, in <module>
    from drozer.ssl.provider import Provider
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.1-py2.7.egg/drozer/ssl/provider.py", line 2, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT
```

### Environment

**Operating system**: Debian
**Java Version:** 1.8
**Android Version:** 6.0
**Drozer Version:**  2.4.1
**Install Method:** egg

More information: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843644

This can be fixed by upgrading to pyopenssl 16.2. Will merge fix shortly.

**Comment by HenryHoggard** [comment]
Fixed in https://github.com/mwrlabs/drozer/pull/241.

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
