### ISSUE TITLE
Cannot use run shell module

### ISSUE THREAD

**Issue by jgarci40** [mwrlabs/drozer#249]
### Steps to reproduce
1. Run drozer console connect in debug mode
2. Send a shell exec command

### Expected behaviour
The shell command should be executed

### Actual behaviour
Here's an example:

drozer Console (v2.4.2 debug mode)
dz> run shell.exec "sleep 1"
exception in module: RuntimeError: drozer could not find or compile a required extension library.

Traceback (most recent call last):
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/drozer/modules/shell/startexec.py", line 41, in execute
    self.stdout.write("%s\n" % self.shellExec(arguments.command))
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/drozer/modules/common/shell.py", line 15, in shellExec
    ShellWrapper = self.loadClass("common/ShellWrapper.apk", "ShellWrapper")
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/drozer/modules/common/loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/pydiesel/reflection/utils/class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "/Users/joshua/anaconda/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/pydiesel/reflection/utils/class_loader.py", line 51, in getClassLoader
    raise RuntimeError("drozer could not find or compile a required extension library.\n")
RuntimeError: drozer could not find or compile a required extension library.

### Environment

**Operating system**:
macOS Sierra Version 10.12.2

**Java Version:**
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Android Version:**
Android 5.0 (Google APIs)

**Drozer Version:** 
drozer Console (v2.4.2 debug mode)

**Install Method:** Built from source/.deb/.exe/..
Built from source using python setup.py

### Drozer Config
```
Contents of ~/.drozer_config
```
[remotes]
https|//raw.github.com/mwrlabs/drozer-modules/repository/ = https://raw.github.com/mwrlabs/drozer-modules/repository/

[repositories]
/Users/joshua/drozer_module_repo = /Users/joshua/drozer_module_repo

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```
[drozer_error.log.zip](https://github.com/mwrlabs/drozer/files/758223/drozer_error.log.zip)

**Comment by jgarci40** [comment]
When I run ```make apks```, I get the following error:

joshua@dhcp-022090:~/source/drozer$ make apks
cd src/drozer/modules/common/; javac -cp /Users/joshua/source/drozer/src/drozer/lib/android.jar ByteStreamReader.java
cd src/drozer/modules/common/; dx --dex --output=ByteStreamReader.apk ByteStreamReader*.class

PARSE ERROR:
unsupported class file version 52.0
...while parsing ByteStreamReader.class
1 error; aborting
make: *** [src/drozer/modules/common/ByteStreamReader.apk] Error 1
rm src/drozer/modules/common/ByteStreamReader.class

I guess this has something to do with the java or JDK version I'm using, but I'm not sure what to do.

**Comment by jgarci40** [comment]
I think I solved the issue. I had to modify the MAKEFILE at the following lines:

```
%.class: %.java
	cd $(dir $^); $(JAVAC) -source 1.7 -target 1.7 -cp $(SDK) $(notdir $^)
```

Essentially, I added the ```-source 1.7 -target 1.7``` arguments to ensure that the dex files get java 1.7 class files. This allowed me to use shell exec again. I will close this issue for now. Thank you for the help, HenryHoggard!

**Comment by jgarci40** [comment]
Also, I think it would be a good idea if the ```make apks``` command was added to the ```Building from source``` section of the README, so that other issues like this are minimized.

**Comment by jgarci40** [comment]
Along the same lines as above, should the MAKEFILE be updated, in GitHub, as I did for my own working copy of the repo?
