### ISSUE TITLE
Drozer could not find or compile a required extension library.

### ISSUE THREAD

**Issue by pandaria89** [mwrlabs/drozer#250]
### Steps to reproduce
1. run drozer
2. issuing a command "run app.broadcast.sniff --action "package.OUTGOING_INTENT"

### Expected behaviour

These should be printed and start sniffing intents:
[\*] Broadcast receiver registered to sniff matching intents
[\*] Output is updated once a second. Press Control+C to exit.

### Actual behaviour

drozer could not find or compile a required extension library.

### Environment

**Operating system**:
Linux Ubuntu 14.04 LTS 64bit 

**Java Version:**
1.6.0_40

**Drozer Version:** 
v2.4.2

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```
[executables]
java=/usr/bin/java

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.2-py2.7.egg/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.2-py2.7.egg/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.2-py2.7.egg/drozer/modules/app/broadcast.py", line 181, in execute
    cl = self.loadClass("common/RegisterReceiver.apk", "RegisterReceiver")
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.2-py2.7.egg/drozer/modules/common/loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.2-py2.7.egg/pydiesel/reflection/utils/class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "/usr/local/lib/python2.7/dist-packages/drozer-2.4.2-py2.7.egg/pydiesel/reflection/utils/class_loader.py", line 51, in getClassLoader
    raise RuntimeError("drozer could not find or compile a required extension library.\n")
RuntimeError: drozer could not find or compile a required extension library

**Comment by jakev** [comment]
I just received this error on Ubuntu LTS 16 when attempting to execute a module when I built from source. I ended up removing the 'drozer' pip package and installing using the deb:

```
sudo apt-get update
sudo apt-get install python-twisted python-openssl python-protobuf
sudo dpkg -i drozer-2.x.x.deb
```
 Hope this helps.

**Comment by HenryHoggard** [comment]
If you are compiling from source remember to run `make apks` first.

Duplicates: https://github.com/mwrlabs/drozer/issues?utf8=%E2%9C%93&q=required%20extension

**Comment by jakev** [comment]
Sorry to reopen - but is it worth adding that to the README? I didn't see that step when attempting to build from source.
