### ISSUE TITLE
make apks asking for java 8 for java binary

### ISSUE THREAD

**Issue by anantshri** [mwrlabs/drozer#258]
When building drozer from source and make apks step if the default java is marked as java 7 then there is compile error.

output attached

```
vagrant@debian-jessie:/vagrant/Build/drozer/source$ javac -version
javac 1.7.0_121
vagrant@debian-jessie:/vagrant/Build/drozer/source$ java -version
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
vagrant@debian-jessie:/vagrant/Build/drozer/source$ make clean
find -name *.pyc |xargs rm -f
rm -f src/drozer/modules/common/ByteStreamReader.class src/drozer/modules/common/ByteStreamWriter.class src/drozer/modules/common/FileUtil.class src/drozer/modules/common/JdwpBroker.class src/drozer/modules/common/Native.class src/drozer/modules/common/RegisterReceiver.class src/drozer/modules/common/ServiceBinder.class src/drozer/modules/common/ShellWrapper.class src/drozer/modules/common/XmlAssetReader.class src/drozer/modules/common/ZipUtil.class src/drozer/modules/scanner/misc/SecretCodes.class src/drozer/modules/common/ByteStreamReader.apk src/drozer/modules/common/ByteStreamWriter.apk src/drozer/modules/common/FileUtil.apk src/drozer/modules/common/JdwpBroker.apk src/drozer/modules/common/Native.apk src/drozer/modules/common/RegisterReceiver.apk src/drozer/modules/common/ServiceBinder.apk src/drozer/modules/common/ShellWrapper.apk src/drozer/modules/common/XmlAssetReader.apk src/drozer/modules/common/ZipUtil.apk src/drozer/modules/scanner/misc/SecretCodes.apk
vagrant@debian-jessie:/vagrant/Build/drozer/source$ make apks
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ByteStreamReader.java
cd src/drozer/modules/common/; dx --dex --output=ByteStreamReader.apk ByteStreamReader*.class
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Makefile:37: recipe for target 'src/drozer/modules/common/ByteStreamReader.apk' failed
make: *** [src/drozer/modules/common/ByteStreamReader.apk] Error 1
rm src/drozer/modules/common/ByteStreamReader.class
```

Then if i use update java alternatives command to set java binary to a java 8 but still javac is marked to 7 version only this works.

```
vagrant@debian-jessie:/vagrant/Build/drozer/source$ sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for mozilla-javaplugin.so
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
vagrant@debian-jessie:/vagrant/Build/drozer/source$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
vagrant@debian-jessie:/vagrant/Build/drozer/source$ javac -version
javac 1.7.0_121
vagrant@debian-jessie:/vagrant/Build/drozer/source$ make apks
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ByteStreamReader.java
cd src/drozer/modules/common/; dx --dex --output=ByteStreamReader.apk ByteStreamReader*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ByteStreamWriter.java
cd src/drozer/modules/common/; dx --dex --output=ByteStreamWriter.apk ByteStreamWriter*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar FileUtil.java
cd src/drozer/modules/common/; dx --dex --output=FileUtil.apk FileUtil*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar JdwpBroker.java
cd src/drozer/modules/common/; dx --dex --output=JdwpBroker.apk JdwpBroker*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar Native.java
cd src/drozer/modules/common/; dx --dex --output=Native.apk Native*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar RegisterReceiver.java
cd src/drozer/modules/common/; dx --dex --output=RegisterReceiver.apk RegisterReceiver*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ServiceBinder.java
cd src/drozer/modules/common/; dx --dex --output=ServiceBinder.apk ServiceBinder*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ShellWrapper.java
cd src/drozer/modules/common/; dx --dex --output=ShellWrapper.apk ShellWrapper*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar XmlAssetReader.java
cd src/drozer/modules/common/; dx --dex --output=XmlAssetReader.apk XmlAssetReader*.class
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ZipUtil.java
cd src/drozer/modules/common/; dx --dex --output=ZipUtil.apk ZipUtil*.class
cd src/drozer/modules/scanner/misc/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar SecretCodes.java
cd src/drozer/modules/scanner/misc/; dx --dex --output=SecretCodes.apk SecretCodes*.class
rm src/drozer/modules/common/ByteStreamWriter.class src/drozer/modules/common/XmlAssetReader.class src/drozer/modules/common/FileUtil.class src/drozer/modules/common/Native.class src/drozer/modules/common/ZipUtil.class src/drozer/modules/scanner/misc/SecretCodes.class src/drozer/modules/common/ServiceBinder.class src/drozer/modules/common/JdwpBroker.class src/drozer/modules/common/ByteStreamReader.class src/drozer/modules/common/ShellWrapper.class src/drozer/modules/common/RegisterReceiver.class
vagrant@debian-jessie:/vagrant/Build/drozer/source$
```

Any thoughts what could be the reason and how can i spot the issue.

I would not be surprized if its a specific issue of my setup but any thought on what could be the reason?

EDIT: adding more details. Looks like dx from 25.0.2 build tools, the one i am using requires java from 1.8 i.e. java 8. its not working with java 7.

**Comment by HenryHoggard** [comment]
Hi @anantshri thanks for the report. Can you try on the 2.4.2 tag and see if you are still getting this issue:
```
git checkout tags/2.4.2
make apks
```

**Comment by anantshri** [comment]
@HenryHoggard as you can see the last edit. its not drozer code. I double checked its the dx.jar for build tools 25.0.2 that are fixed on java 8 so not sure if drozer can do anything about this. 

BTW what's the build tool versions you folks are using at your end.

I will close this issue as this is not drozer related but rather build tools on android side.

**Comment by anantshri** [comment]
more probing confirms since build tools version 24.0.0 they are compiled with java 8 and hence need java 8 is required to execute.
