### ISSUE TITLE
I am getting this error 

### ISSUE THREAD

**Issue by ladyleet1337** [mwrlabs/drozer#265]
When i type make apks

d src/drozer/modules/scanner/misc/; javac -cp /home/gayatri/drozer/src/drozer/lib/android.jar SecretCodes.java
cd src/drozer/modules/scanner/misc/; /home/gayatri/drozer/src/drozer/lib/dx --dex --output=SecretCodes.apk SecretCodes*.class

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:665)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
	at com.android.dx.command.dexer.Main.run(Main.java:230)
	at com.android.dx.command.dexer.Main.main(Main.java:199)
	at com.android.dx.command.Main.main(Main.java:103)
...while parsing SecretCodes.class

1 error; aborting
Makefile:37: recipe for target 'src/drozer/modules/scanner/misc/SecretCodes.apk' failed
make: *** [src/drozer/modules/scanner/misc/SecretCodes.apk] Error 1
rm src/drozer/modules/scanner/misc/SecretCodes.class

**Comment by amarekano** [comment]
@ladyleet1337 which version of the java are you using on this system?

**Comment by Epsiloni** [comment]
Try using Java 7.
export JAVA_HOME=`/usr/libexec/java_home -v 1.7`

**Comment by amarekano** [comment]
Closed due to lack of response. Please reopen if you're still having an issue.

**Comment by majordjuj** [comment]
Hello, I'm having the same error. I'm using java 1.8

**Comment by majordjuj** [comment]
Hello, I'm having the same error. I'm using java 1.8

**Comment by amarekano** [comment]
Hi @majordjuj, drozer doesn't support java 1.8 yet. You will have to downgrade to java 1.7 in order to use drozer.

**Comment by majordjuj** [comment]
OK, indeed, with the good version of java it works well.
I'm having another error message after compilation...
error: can't copy 'scripts/drozer': doesn't exist or not a regular file
Do I've to start another issue ?

**Comment by amarekano** [comment]
Yes please. Before you open an issue please make sure you're using our latest drozer release. This can be downloaded at https://github.com/mwrlabs/drozer/releases/tag/2.4.2.

**Comment by pgargey** [comment]
This is still an issue.
With latest Drozer and on my set up I have Java 1.8

**Comment by nksCH** [comment]
Can confirm.
