### ISSUE TITLE
RuntimeError: drozer could not find or compile a required extension library.

### ISSUE THREAD

**Issue by soupwaylee** [mwrlabs/drozer#306]
### Steps to reproduce
1. Set Python version 2.7.14 with pyenv. Set java 1.7 in drozer directory with jenv
2. Installed all Python packages mentioned in the Readme
3. ran `python setup.py bdist_wheel`
3. (Successfully) ran `make apks` before installing Python Wheel
4. (Successfully) ran `sudo pip install drozer-2.4.3-py2-none-any.whl` in `drozer/dist`

### Expected behaviour
Ran `run scanner.provider.finduris -a <appname>`, got RuntimeError: drozer could not find or compile a required extension library. 
(I have no ~/.drozer_config file - could that be the issue?). 

### Environment

**Operating system**: mac OS X v10.12.6 

**Java Version:** oracle64-1.7.0.80

**Drozer Version:** 2.4.3

**Install Method:** Built from source

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
dz> run scanner.provider.finduris -a <appname>
Scanning <appname>...
exception in module: RuntimeError: drozer could not find or compile a required extension library.
Traceback (most recent call last):
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/scanner/provider/find_uris.py", line 23, in execute
    for uri in self.findAllContentUris(arguments.package):
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 206, in findAllContentUris
    uris = uris.union(self.__search_package(package))
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 316, in __search_package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 228, in findContentUris
    dex_file = self.extractFromZip("classes.dex", path, self.cacheDir())
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/zip_file.py", line 14, in extractFromZip
    ZipUtil = self.loadClass("common/ZipUtil.apk", "ZipUtil")
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "/Users/stfnsu/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 51, in getClassLoader
    raise RuntimeError("drozer could not find or compile a required extension library.\n")
```

**Comment by amarekano** [comment]
Hey @soupwaylee, could you try installing our release package for drozer 2.4.3 and let us know how that goes.
https://github.com/mwrlabs/drozer/releases/download/2.4.3/drozer-2.4.3-py2-none-any.whl

**Comment by soupwaylee** [comment]
Hi @amarekano thank you for replying, I installed that version last week and it works for me now! 
The instructions [here](https://blog.ropnop.com/installing-drozer-on-os-x-el-capitan/) were helpful.
What could be the cause to this issue?

**Comment by amarekano** [comment]
I suspect when you built it from source for some reason it didn't generate the apks or if the apks were generated they were packaged with the python wheel. Which is one of the reasons you get the "drozer could not find or compile a required extension library." error. It may 

I'm glad you've got this working. If you're still unable to rebuild drozer from source for OSX please reopen this issue.
