### ISSUE TITLE
ssl issues - no SSL_ST_INIT

### ISSUE THREAD

**Issue by lucasduffey** [mwrlabs/drozer#320]
### Steps to reproduce
1. drozer console connect

### Expected behaviour
Tell us what should happen.

### Actual behaviour
```
$ drozer console connect
Traceback (most recent call last):
  File "/usr/bin/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/usr/local/lib/python2.7/dist-packages/drozer/cli/console.py", line 8, in <module>
  File "/usr/local/lib/python2.7/dist-packages/drozer/console/__init__.py", line 4, in <module>
  File "/usr/local/lib/python2.7/dist-packages/drozer/console/console.py", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pydiesel/api/transport/__init__.py", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pydiesel/api/transport/socket_transport.py", line 8, in <module>
  File "/usr/local/lib/python2.7/dist-packages/drozer/ssl/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/drozer/ssl/ssl_manager.py", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/drozer/ssl/provider.py", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

### Environment

**Operating system**: Ubuntu 16 LTS

**Java Version:**
```
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Android Version:**

**Drozer Version:** 

**Install Method:** installed deb from drozer website

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by lucasduffey** [comment]
https://github.com/mwrlabs/drozer/issues/239 indicates pyopenssl might need to be updated to 16.2

Would help if there was some sort of `requirements.txt` to install dependencies

**Comment by HenryHoggard** [comment]
What version of pyopenssl do you have

**Comment by lucasduffey** [comment]
```
$ pip search pyopenssl
  INSTALLED: 17.5.0 (latest)
```

**Comment by HenryHoggard** [comment]
As mentioned in in the readme it needs pyopenssl 16.2 or greater. Install pyopenssl using pip to get newer version. Closing issue.

**Comment by lucasduffey** [comment]
doesn't fix the problem

**Comment by lucasduffey** [comment]
figured it out, pip now points to "pip3" so you have to use pip2 to install python2 packages
```
pip2 uninstall pyOpenSSL
pip2 uninstall twisted
```

**Comment by HenryHoggard** [comment]
You need to be on Artful or Bionic for Ubuntu, or Stretch, Buster or sid for Debian to get the correct version of pyopenssl. But pip is recommended anyway.

**Comment by Hariprasanth03SN** [comment]
Traceback (most recent call last):
  File "/usr/bin/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/usr/lib/python2.7/dist-packages/drozer/cli/console.py", line 8, in <module>
    from drozer.console import Console
  File "/usr/lib/python2.7/dist-packages/drozer/console/__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "/usr/lib/python2.7/dist-packages/drozer/console/console.py", line 5, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/lib/python2.7/dist-packages/pydiesel/api/__init__.py", line 9, in <module>
    from pydiesel.api.frame import Frame
  File "/usr/lib/python2.7/dist-packages/pydiesel/api/frame.py", line 3, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/lib/python2.7/dist-packages/pydiesel/api/protobuf_pb2.py", line 4, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

pls help
