### ISSUE TITLE
Error when running `drozer console connect`: No module named drozer.cli.console

### ISSUE THREAD

**Issue by mydockergit** [mwrlabs/drozer#342]
Hi,

I have the same issue on Windows 10 x64:  
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\drozer\Scripts\drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console
```

This is my **USER** environment variables:
```
C:\Program Files\Java\jre1.8.0_121
C:\Python27
```
This is my **SYSTEM** environment variables:
```
C:\Program Files\Java\jre1.8.0_121
C:\Python27
```

I noticed that here https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge you mentioned that I need to update `PATH`, `PYTHONPATH `and `SDK`  which you didn't specify on the main page of [GitHub](
https://github.com/mwrlabs/drozer), you should update the main page it will safe you questions by other people.  

In the `PYTHONPATH` I didn't understand what you mean by: `/path/to/drozer/src` and `/path/to/drozer/test`.  
These folder are not exist with the windows installation.
After I installed Drozer on Windows, using the MSI, I go two folders:
```
List
Scripts
```  

Bot of them don't contain `src` and `test` folders.  

### Expected behaviour
Run smoothly

### Actual behaviour
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\drozer\Scripts\drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console
```

### Environment
This is my **USER** environment variables:
```
C:\Program Files\Java\jre1.8.0_121
C:\Python27
```
This is my **SYSTEM** environment variables:
```
C:\Program Files\Java\jre1.8.0_121
C:\Python27
```

**Operating system**:
Windows 10 x64
**Java Version:**
1.8
**Android Version:**

**Drozer Version:** 

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```
I don't have in the windows installation with MSI.
### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by mydockergit** [comment]
Fixed it after I set `PYTHONPATH`  in the USER environment variables to:  
`C:\..\drozer\Lib\site-packages`
